// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjON6MEEZBfZy3_C3R_3PCGVaJbSZrjnk',
    appId: '1:256323952799:web:c05cd2173c3b4949b582aa',
    messagingSenderId: '256323952799',
    projectId: 'stock-plus-app',
    authDomain: 'stock-plus-app.firebaseapp.com',
    storageBucket: 'stock-plus-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDo8Oo6Pf-cue-_UfTMkP4Gy0ZsttdO8',
    appId: '1:256323952799:android:056ca2d0b3bebb6db582aa',
    messagingSenderId: '256323952799',
    projectId: 'stock-plus-app',
    storageBucket: 'stock-plus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKyqzu9rfFKRQlxz7jP1Weqzax5ZCt8s',
    appId: '1:256323952799:ios:1151dbffbc73c6c1b582aa',
    messagingSenderId: '256323952799',
    projectId: 'stock-plus-app',
    storageBucket: 'stock-plus-app.appspot.com',
    iosBundleId: 'com.example.stockPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKyqzu9rfFKRQlxz7jP1Weqzax5ZCt8s',
    appId: '1:256323952799:ios:0698c690e1bec903b582aa',
    messagingSenderId: '256323952799',
    projectId: 'stock-plus-app',
    storageBucket: 'stock-plus-app.appspot.com',
    iosBundleId: 'com.example.stockPlus.RunnerTests',
  );
}
